/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-i-279drWMetkv28FextP8bgN3T0m8c',
    appId: '1:670969435559:web:560a43acb2531a45709282',
    messagingSenderId: '670969435559',
    projectId: 'fincore-mobile',
    authDomain: 'fincore-mobile.firebaseapp.com',
    storageBucket: 'fincore-mobile.appspot.com',
    measurementId: 'G-KR6GR20GYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChD3t8lgP3sccxZ03LJ6JMI0vMWuo5V8c',
    appId: '1:670969435559:android:2bb036073906e6c2709282',
    messagingSenderId: '670969435559',
    projectId: 'fincore-mobile',
    storageBucket: 'fincore-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Bi64evZz7VZoj94SsYQoPscTEHNatkA',
    appId: '1:670969435559:ios:48fc9025abae78e7709282',
    messagingSenderId: '670969435559',
    projectId: 'fincore-mobile',
    storageBucket: 'fincore-mobile.appspot.com',
    iosBundleId: 'com.csh.tallyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Bi64evZz7VZoj94SsYQoPscTEHNatkA',
    appId: '1:670969435559:ios:0b21cf3f35b3f301709282',
    messagingSenderId: '670969435559',
    projectId: 'fincore-mobile',
    storageBucket: 'fincore-mobile.appspot.com',
    iosBundleId: 'com.example.abc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-i-279drWMetkv28FextP8bgN3T0m8c',
    appId: '1:670969435559:web:df5d16adde645047709282',
    messagingSenderId: '670969435559',
    projectId: 'fincore-mobile',
    authDomain: 'fincore-mobile.firebaseapp.com',
    storageBucket: 'fincore-mobile.appspot.com',
    measurementId: 'G-YF8YJGHR2Z',
  );

}*/
